baseURL: https://blog.nelhage.com
disablePathToLower: true
languageCode: en-us
title: Made of Bugs
googleAnalytics: UA-10238083-1
MetaDataFormat: yaml
theme: nelhage
outputFormats:
  RSS:
    BaseName: atom
taxonomies: []
permalinks:
  post: /post/:slug
params:
  Author: Nelson Elhage
  Subtitle: It's software. It's made of bugs.
PygmentsCodeFences: true
...
