#!/bin/bash
set -ex
cd "$(dirname "$0")/.."
draft=
if [ "$1" = "--drafts" ]; then
    draft=-D
fi
hugo --cleanDestinationDir $draft
git push
rsync -vax --delete public/ nelhage.com:/opt/www/blog.nelhage.com/
