#!/bin/bash
set -ex
cd "$(dirname "$0")/.."
draft=
if [ "$1" = "--drafts" ]; then
    draft=-D
fi
git push
hugo -F --cleanDestinationDir $draft
rsync -vax --delete public/ nelhage.com:/opt/www/blog.nelhage.com/
