#!/usr/bin/env python

import os
import sys

corpus = "hither and thither"
indexes = range(len(corpus))

indexes.sort(key=lambda i: corpus[i:])

print "<table class='diagram'>"
print "<tr class='index'>"
for i in xrange(len(corpus)):
    sys.stdout.write("<td>%d</td>" % (i,))
print
print "</tr>"
print "<tr>"
for c in corpus:
    sys.stdout.write("<td>%s</td>" % (c,))
print
print "</tr>"
print "</table>"

print "<div style='padding: 1em;'></div>"

print "<table class='diagram'>"
print "<tr> <th>Index</th> <th colspan='5'>Suffix</th> </tr>"
for i in indexes:
    print "<tr>"
    print "<td class='index'>%d</td>" % (i,)
    for chr in corpus[i:]:
        sys.stdout.write("<td>%s</td>" % (chr.replace(' ', '&nbsp;')))
    print
    print "</tr>"

print "</table>"
