#!/usr/bin/env python3
import re
import sys

if len(sys.argv) > 1:
  with open(sys.argv[1]) as fh:
    data = fh.read()
else:
  data = sys.stdin.read()

data = re.sub(
  r'^[*][*]([^\n]+)[*][*]$',
  r'### \1',
  data,
  flags=re.M|re.S,
)

sys.stdout.write(data)
